name: 每日早报定时推送
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # 每天早上8点推送
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 安装python环境
        uses: actions/setup-python@v3

      - name: 安装依赖
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 开始推送
        env:
          wpush_apikey: ${{ secrets.WPUSH_APIKEY }} # wpush apikey
          alapi_token: ${{ secrets.ALAPI_TOKEN }}
          type: ${{ secrets.TYPE }}
          channel: ${{ secrets.CHANNEL }}
        run: |
          python main.py
